### ISSUE TITLE
Allow backticks escaping 

### ISSUE THREAD

**Issue by tacone** [jsdf/coffee-react-transform#50]
Hello, thank you for the good work.
I'm running into an issue with my IDE (webstorm)

This works properly
```
RouteCore.map ->
    @route '/', (ctx) -> <HomePage />
```

This does not:
```
RouteCore.map ->
    @route '/', (ctx) -> `<HomePage />`
```

Simply put, the first works well, but completely breaks the IDE, the second fails to build, but does not break the IDE:

```
   router.cjsx:12:20: Unexpected token <
```

I'm using https://atmospherejs.com/jhartma/cjsx which reportedly uses this package. I wonder if there is any workaround I can use or if it's feasible to allow backtick escaping of any kind.

**Comment by jsdf** [comment]
Anything inside backticks is treated as regular JS, so it is passed through the transformer and the Coffeescript compiler untouched. Thus it would be present in the JS output. You could try running the regular react-tools JSX transformer on the output JS to then transform the tags which were passed through, but in that case coffee-react-transform wouldn't actually be doing anything. 

Anything inside the backticks is JS, not Coffeescript, which means we can't apply the transformation to it, because it transforms CJSX -> Coffeescript, but inside the backticks you need JSX -> JS.

I would recommend trying to extend your IDE's syntax definitions to understand CJSX.

**Comment by tacone** [comment]
Thank you for your answer :)
